### ISSUE TITLE
Develop a microservice that sends tasks to a Spark cluster in response to Kafka messages

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/data-analyses-scheduler#1]
The microservice has the following functionalities:
1. Accept a yml or json configuration file mapping a Kafka topic to a list of Spark scripts. E.g.:
   
   ```
   topic1:
       script1:
           [dependencies: list_of_dependencies_need_to_run_the_script]
       script2:
           [dependencies: list_of_dependencies_need_to_run_the_script]
   topic2:
       script3:
           [dependencies: list_of_dependencies_need_to_run_the_script]
   ```
   
   Note: Use the following library to transparently handle the configuration file: https://github.com/spf13/viper. Give a look at the [benchflow-client](https://github.com/benchflow/client) for an example on how to use Viper.
2. Wrap the [spark-submit](http://spark.apache.org/docs/latest/submitting-applications.html) tool.
3. Listen to the Kafka topics described in the configuration file. It starts different go routines listening for a topic each. For the interaction with Kafka we must use a protocol that ensure that we don't loose messages.
4. Submit Tasks to Spark, according to the configuration file. Use the [Builder pattern](https://en.wikipedia.org/wiki/Builder_pattern) to build the spark-submit commands. Example here: https://github.com/benchflow/client/tree/dev/src/cloud/benchflow/utils/docker. The script must be submitted with the cluster mode because we don't want to wait for the result.
5. Runs in a Docker container that obtain Spark scripts for the following two benchflow repositories: https://github.com/benchflow/analysers, https://github.com/benchflow/data-transformers and make them available for the submission to Spark.

**Comment by VincenzoFerme** [comment]
@Cerfoglg I slightly changed points: 1 and 4.

**Comment by Cerfoglg** [comment]
Additional notes:
- Wrap Spark-submit alongside the necessary most common dependencies
- Test against a YARN cluster
