### ISSUE TITLE
Move configurations for data-transformers in the correct folders

### ISSUE THREAD

**Issue by Cerfoglg** [benchflow/data-analyses-scheduler#23]
Given that for different WfMS we require different configurations for the data-transformers, we need to organise the configuration files so that they can be retrieved by the spark tasks sender upon submitting the script to Spark depending on the SUT the collected data refers to.

The configurations should be placed in the folder /app/configuration/data-transformers/, and the naming for the yaml configuration files should be `<engine_name>.data-transformers.yml`, where engine_name refers to the SUT (Example: camunda).

**Comment by VincenzoFerme** [comment]
Already done.
