### ISSUE TITLE
Schedule Experiment Metrics after all the Experiment's Trial Metrics have been Computed

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/data-analyses-scheduler#27]
~~We are going to add experiment metrics (see https://github.com/benchflow/analysers/issues/22). These metrics can be computed only after the metrics for all the trials belonging to the given experiment have been computed. For doing that we added the `Total number of trials for the current experiment` in the Kafka message we receive for computing metrics, so that we can count how many trials of the given experiment have been computed in a tmp variable, and when we have computed metrics for all the trials, we launch the experiment metrics and remove the information from the tmp variable.~~ Fixed by #28 

The computations should be performed in parallel (by limiting the number of tasks that can run in parallel), when possible according to the data-flow dependencies.

**Comment by Cerfoglg** [comment]
@VincenzoFerme This issue needs closing, since we do now launch experiments when analysers are finished

**Comment by VincenzoFerme** [comment]
It was open because of: 

> The computations should be performed in parallel (by limiting the number of tasks that can run in parallel), when possible according to the data-flow dependencies.

But I close it anyway since we have #9
