### ISSUE TITLE
Receive Container ID value from Kafka and pass it to transformer scripts

### ISSUE THREAD

**Issue by Cerfoglg** [benchflow/data-analyses-scheduler#40]
Our current implementation does not receive container IDs over Kafka. This data is required for our transformers, primarily our stats transformer, to identify the container the collected data to transform belongs to.

Modify the current implementation so that:
- Kafka messages now can receive a container_id value from the collectors
- Transformer scripts will be sent the container_id value when submitted to Spark

**Comment by VincenzoFerme** [comment]
@Cerfoglg are you sure we did not change our mind on it and sending multiple Minio keys?
