### ISSUE TITLE
Correct Management of Errors to Retry

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/data-analyses-scheduler#87]
The following check should be [case insensitive](https://gistpages.com/posts/go-lang-case-insensitive-contains): https://github.com/benchflow/data-analyses-scheduler/blob/416cf6689338e52849799e66c603a8a36d140743/src/cloud/benchflow/data-analyses-scheduler/scripts/scriptSubmission.go#L52

Moreover we had the mentioned check to retry only some Spark error that were not managed. Now you are doing the same also for the new errors you added. Is this fine? I suppose that it is wrong and only some of the detected errors should be retried.

**Comment by Cerfoglg** [comment]
@VincenzoFerme It is case insensitive, I convert to lowercase before checking in the checkError function. 

And ideally only some errors should lead a retry, while others shouldn't, but currently it appears Spark is not consistent at all in the way it reports error, as it doesn't report a script crashing half the times. At some point this should be explored further, to find out exactly how to catch and handle all potential errors.
